import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { formatQuoteNumber } from "@/lib/quote-number";

export { formatQuoteNumber };

export type QuoteLineItem = {
  description: string;
  quantity: number;
  unitPrice: number; // cents
};

export type QuoteDocumentProps = {
  quoteNumber: number;
  businessName: string;
  lead: { name: string; email: string | null; company: string | null };
  lineItems: QuoteLineItem[];
  totalAmount: number; // cents
  currency: string;
  generatedAt: Date;
};

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { marginBottom: 24 },
  businessName: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  meta: { color: "#555", marginBottom: 2 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 6 },
  table: { display: "flex", flexDirection: "column", borderTop: "1px solid #ddd" },
  row: {
    flexDirection: "row",
    borderBottom: "1px solid #eee",
    paddingVertical: 6,
  },
  headerRow: { fontWeight: 700, backgroundColor: "#f5f5f5" },
  colDescription: { flex: 3 },
  colQuantity: { flex: 1, textAlign: "right" },
  colUnitPrice: { flex: 1, textAlign: "right" },
  colLineTotal: { flex: 1, textAlign: "right" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 12,
    paddingTop: 8,
    borderTop: "1px solid #333",
  },
  totalLabel: { fontWeight: 700, marginRight: 12 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, color: "#999", fontSize: 9 },
});

function formatMoney(cents: number, currency: string) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(cents / 100);
}

export function QuoteDocument({
  quoteNumber,
  businessName,
  lead,
  lineItems,
  totalAmount,
  currency,
  generatedAt,
}: QuoteDocumentProps) {
  return (
    <Document title={`Quote ${formatQuoteNumber(quoteNumber)}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.businessName}>{businessName}</Text>
          <Text style={styles.meta}>Quote #{formatQuoteNumber(quoteNumber)}</Text>
          <Text style={styles.meta}>Date: {generatedAt.toLocaleDateString("en-US")}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Prepared for</Text>
          <Text>{lead.name}</Text>
          {lead.company ? <Text>{lead.company}</Text> : null}
          {lead.email ? <Text>{lead.email}</Text> : null}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Line Items</Text>
          <View style={styles.table}>
            <View style={[styles.row, styles.headerRow]}>
              <Text style={styles.colDescription}>Description</Text>
              <Text style={styles.colQuantity}>Qty</Text>
              <Text style={styles.colUnitPrice}>Unit Price</Text>
              <Text style={styles.colLineTotal}>Total</Text>
            </View>
            {lineItems.map((item, i) => (
              <View style={styles.row} key={i}>
                <Text style={styles.colDescription}>{item.description}</Text>
                <Text style={styles.colQuantity}>{item.quantity}</Text>
                <Text style={styles.colUnitPrice}>{formatMoney(item.unitPrice, currency)}</Text>
                <Text style={styles.colLineTotal}>
                  {formatMoney(item.unitPrice * item.quantity, currency)}
                </Text>
              </View>
            ))}
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total</Text>
            <Text>{formatMoney(totalAmount, currency)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by {businessName}&apos;s pipeline automation tool. This is a demo quote.
        </Text>
      </Page>
    </Document>
  );
}
